/**
 * Modelos Apple com cores e armazenamentos oficiais (pt-BR, fonte: Apple).
 * Usado para pré-preencher o cadastro de Produto na JM Store — o lojista
 * escolhe o modelo e as cores/armazenamentos vêm prontos (editáveis).
 * iPhone: linha completa do 17 até o 6. Ampliar = adicionar entradas aqui.
 */
export interface AppleModelo { nome: string; linha: 'iPhone' | 'iPad' | 'Mac' | 'Watch'; cores: string[]; armazenamentos: string[] }

export const APPLE_MODELOS: AppleModelo[] = [
  // ── iPhone 17 / Air / 17e ──
  { nome: 'iPhone 17 Pro Max', linha: 'iPhone', cores: ['Prateado', 'Laranja-cósmico', 'Azul-intenso'], armazenamentos: ['256GB', '512GB', '1TB', '2TB'] },
  { nome: 'iPhone 17 Pro', linha: 'iPhone', cores: ['Prateado', 'Laranja-cósmico', 'Azul-intenso'], armazenamentos: ['256GB', '512GB', '1TB'] },
  { nome: 'iPhone 17', linha: 'iPhone', cores: ['Preto', 'Branco', 'Azul-névoa', 'Sálvia', 'Lavanda'], armazenamentos: ['256GB', '512GB'] },
  { nome: 'iPhone Air', linha: 'iPhone', cores: ['Preto-espacial', 'Branco-nuvem', 'Dourado-claro', 'Azul-céu'], armazenamentos: ['256GB', '512GB', '1TB'] },
  { nome: 'iPhone 17e', linha: 'iPhone', cores: ['Preto', 'Branco', 'Rosa-pálido'], armazenamentos: ['256GB', '512GB'] },
  // ── iPhone 16 / 16e ──
  { nome: 'iPhone 16 Pro Max', linha: 'iPhone', cores: ['Titânio Preto', 'Titânio Branco', 'Titânio Natural', 'Titânio-deserto'], armazenamentos: ['256GB', '512GB', '1TB'] },
  { nome: 'iPhone 16 Pro', linha: 'iPhone', cores: ['Titânio Preto', 'Titânio Branco', 'Titânio Natural', 'Titânio-deserto'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 16 Plus', linha: 'iPhone', cores: ['Preto', 'Branco', 'Rosa', 'Verde-acinzentado', 'Ultramarino'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 16', linha: 'iPhone', cores: ['Preto', 'Branco', 'Rosa', 'Verde-acinzentado', 'Ultramarino'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 16e', linha: 'iPhone', cores: ['Preto', 'Branco'], armazenamentos: ['128GB', '256GB', '512GB'] },
  // ── iPhone 15 ──
  { nome: 'iPhone 15 Pro Max', linha: 'iPhone', cores: ['Titânio Preto', 'Titânio Branco', 'Titânio Azul', 'Titânio Natural'], armazenamentos: ['256GB', '512GB', '1TB'] },
  { nome: 'iPhone 15 Pro', linha: 'iPhone', cores: ['Titânio Preto', 'Titânio Branco', 'Titânio Azul', 'Titânio Natural'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 15 Plus', linha: 'iPhone', cores: ['Preto', 'Azul', 'Verde', 'Amarelo', 'Rosa'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 15', linha: 'iPhone', cores: ['Preto', 'Azul', 'Verde', 'Amarelo', 'Rosa'], armazenamentos: ['128GB', '256GB', '512GB'] },
  // ── iPhone 14 ──
  { nome: 'iPhone 14 Pro Max', linha: 'iPhone', cores: ['Prateado', 'Dourado', 'Preto-espacial', 'Roxo-profundo'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 14 Pro', linha: 'iPhone', cores: ['Prateado', 'Dourado', 'Preto-espacial', 'Roxo-profundo'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 14 Plus', linha: 'iPhone', cores: ['Meia-noite', 'Estelar', '(PRODUCT)RED', 'Azul', 'Roxo', 'Amarelo'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 14', linha: 'iPhone', cores: ['Meia-noite', 'Estelar', '(PRODUCT)RED', 'Azul', 'Roxo', 'Amarelo'], armazenamentos: ['128GB', '256GB', '512GB'] },
  // ── iPhone SE 3 ──
  { nome: 'iPhone SE (3ª geração)', linha: 'iPhone', cores: ['(PRODUCT)RED', 'Estelar', 'Meia-noite'], armazenamentos: ['64GB', '128GB', '256GB'] },
  // ── iPhone 13 ──
  { nome: 'iPhone 13 Pro Max', linha: 'iPhone', cores: ['Grafite', 'Dourado', 'Prateado', 'Azul-Sierra', 'Verde-alpino'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 13 Pro', linha: 'iPhone', cores: ['Grafite', 'Dourado', 'Prateado', 'Azul-Sierra', 'Verde-alpino'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  { nome: 'iPhone 13', linha: 'iPhone', cores: ['(PRODUCT)RED', 'Estelar', 'Meia-noite', 'Azul', 'Rosa', 'Verde'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 13 mini', linha: 'iPhone', cores: ['(PRODUCT)RED', 'Estelar', 'Meia-noite', 'Azul', 'Rosa', 'Verde'], armazenamentos: ['128GB', '256GB', '512GB'] },
  // ── iPhone 12 ──
  { nome: 'iPhone 12 Pro Max', linha: 'iPhone', cores: ['Prateado', 'Grafite', 'Dourado', 'Azul-Pacífico'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 12 Pro', linha: 'iPhone', cores: ['Prateado', 'Grafite', 'Dourado', 'Azul-Pacífico'], armazenamentos: ['128GB', '256GB', '512GB'] },
  { nome: 'iPhone 12', linha: 'iPhone', cores: ['Preto', 'Branco', '(PRODUCT)RED', 'Verde', 'Azul', 'Roxo'], armazenamentos: ['64GB', '128GB', '256GB'] },
  { nome: 'iPhone 12 mini', linha: 'iPhone', cores: ['Preto', 'Branco', '(PRODUCT)RED', 'Verde', 'Azul', 'Roxo'], armazenamentos: ['64GB', '128GB', '256GB'] },
  // ── iPhone SE 2 ──
  { nome: 'iPhone SE (2ª geração)', linha: 'iPhone', cores: ['Branco', 'Preto', '(PRODUCT)RED'], armazenamentos: ['64GB', '128GB', '256GB'] },
  // ── iPhone 11 ──
  { nome: 'iPhone 11 Pro Max', linha: 'iPhone', cores: ['Prateado', 'Cinza-espacial', 'Dourado', 'Verde meia-noite'], armazenamentos: ['64GB', '256GB', '512GB'] },
  { nome: 'iPhone 11 Pro', linha: 'iPhone', cores: ['Prateado', 'Cinza-espacial', 'Dourado', 'Verde meia-noite'], armazenamentos: ['64GB', '256GB', '512GB'] },
  { nome: 'iPhone 11', linha: 'iPhone', cores: ['Roxo', 'Verde', 'Amarelo', 'Preto', 'Branco', '(PRODUCT)RED'], armazenamentos: ['64GB', '128GB', '256GB'] },
  // ── iPhone X ──
  { nome: 'iPhone XS Max', linha: 'iPhone', cores: ['Prateado', 'Cinza-espacial', 'Dourado'], armazenamentos: ['64GB', '256GB', '512GB'] },
  { nome: 'iPhone XS', linha: 'iPhone', cores: ['Prateado', 'Cinza-espacial', 'Dourado'], armazenamentos: ['64GB', '256GB', '512GB'] },
  { nome: 'iPhone XR', linha: 'iPhone', cores: ['Preto', 'Branco', 'Azul', 'Amarelo', 'Coral', '(PRODUCT)RED'], armazenamentos: ['64GB', '128GB', '256GB'] },
  { nome: 'iPhone X', linha: 'iPhone', cores: ['Prateado', 'Cinza-espacial'], armazenamentos: ['64GB', '256GB'] },
  // ── iPhone 8 ──
  { nome: 'iPhone 8 Plus', linha: 'iPhone', cores: ['Dourado', 'Prateado', 'Cinza-espacial', '(PRODUCT)RED'], armazenamentos: ['64GB', '128GB', '256GB'] },
  { nome: 'iPhone 8', linha: 'iPhone', cores: ['Dourado', 'Prateado', 'Cinza-espacial', '(PRODUCT)RED'], armazenamentos: ['64GB', '128GB', '256GB'] },
  // ── iPhone 7 ──
  { nome: 'iPhone 7 Plus', linha: 'iPhone', cores: ['Preto matte', 'Preto brilhante', 'Dourado', 'Ouro rosa', 'Prateado', '(PRODUCT)RED'], armazenamentos: ['32GB', '128GB', '256GB'] },
  { nome: 'iPhone 7', linha: 'iPhone', cores: ['Preto matte', 'Preto brilhante', 'Dourado', 'Ouro rosa', 'Prateado', '(PRODUCT)RED'], armazenamentos: ['32GB', '128GB', '256GB'] },
  // ── iPhone SE 1 / 6s / 6 ──
  { nome: 'iPhone SE (1ª geração)', linha: 'iPhone', cores: ['Cinza-espacial', 'Prateado', 'Dourado', 'Ouro rosa'], armazenamentos: ['16GB', '32GB', '64GB', '128GB'] },
  { nome: 'iPhone 6s Plus', linha: 'iPhone', cores: ['Cinza-espacial', 'Prateado', 'Dourado', 'Ouro rosa'], armazenamentos: ['16GB', '32GB', '64GB', '128GB'] },
  { nome: 'iPhone 6s', linha: 'iPhone', cores: ['Cinza-espacial', 'Prateado', 'Dourado', 'Ouro rosa'], armazenamentos: ['16GB', '32GB', '64GB', '128GB'] },
  { nome: 'iPhone 6 Plus', linha: 'iPhone', cores: ['Cinza-espacial', 'Prateado', 'Dourado'], armazenamentos: ['16GB', '64GB', '128GB'] },
  { nome: 'iPhone 6', linha: 'iPhone', cores: ['Cinza-espacial', 'Prateado', 'Dourado'], armazenamentos: ['16GB', '32GB', '64GB', '128GB'] },
  // ── iPad (exemplos) ──
  { nome: 'iPad Pro 13" (M4)', linha: 'iPad', cores: ['Prateado', 'Preto-espacial'], armazenamentos: ['256GB', '512GB', '1TB', '2TB'] },
  { nome: 'iPad Air 13" (M2)', linha: 'iPad', cores: ['Cinza-espacial', 'Estelar', 'Roxo', 'Azul'], armazenamentos: ['128GB', '256GB', '512GB', '1TB'] },
  // ── Mac (exemplos) ──
  { nome: 'MacBook Air 13" (M3)', linha: 'Mac', cores: ['Meia-noite', 'Estelar', 'Cinza-espacial', 'Prateado'], armazenamentos: ['256GB', '512GB', '1TB', '2TB'] },
  { nome: 'MacBook Pro 14" (M4)', linha: 'Mac', cores: ['Preto-espacial', 'Prateado'], armazenamentos: ['512GB', '1TB', '2TB'] },
  // ── Watch (cores = caixa; "armazenamento" = tamanho) ──
  { nome: 'Apple Watch Series 10', linha: 'Watch', cores: ['Alumínio Preto-jato', 'Alumínio Rosé', 'Alumínio Prateado', 'Titânio Ardósia', 'Titânio Ouro', 'Titânio Natural'], armazenamentos: ['42mm', '46mm'] },
  { nome: 'Apple Watch Ultra 2', linha: 'Watch', cores: ['Titânio Natural', 'Titânio Preto'], armazenamentos: ['49mm'] },
]

// ─────────────────────────────────────────────────────────────────────────────
// Números de modelo (A####) — GERADO a partir de "Iphones.docx", a referência
// oficial da Apple. Não editar à mão: regerar do documento quando sair aparelho
// novo.
//
// O número de modelo é o "A" gravado atrás do aparelho e em Ajustes › Geral ›
// Sobre. Ele identifica o MODELO e a região — NÃO a peça. Todo iPhone 15 Pro Max
// vendido aqui é A3106: não serve para achar duplicata, quem faz isso é o IMEI.
// Capacidade e cor vêm como as opções POSSÍVEIS do modelo, para o operador
// escolher — não como palpite do sistema.
// ─────────────────────────────────────────────────────────────────────────────

export interface ModeloApple {
  modelo: string
  capacidades: string[]
  cores: string[]
}

/**
 * Número de modelo → nome do modelo. Só o nome: cores e capacidades saem de
 * APPLE_MODELOS acima, que é a lista curada e já usada no cadastro de produto.
 * Manter duas listas das mesmas cores faria "Titânio Preto" e "titânio preto"
 * virarem variantes diferentes no estoque.
 */
export const NUMERO_MODELO_APPLE: Record<string, string> = {
  A3575: "iPhone 17e",
  A3635: "iPhone 17e",
  A3634: "iPhone 17e",
  A3257: "iPhone 17 Pro Max",
  A3525: "iPhone 17 Pro Max",
  A3527: "iPhone 17 Pro Max",
  A3526: "iPhone 17 Pro Max",
  A3256: "iPhone 17 Pro",
  A3522: "iPhone 17 Pro",
  A3524: "iPhone 17 Pro",
  A3523: "iPhone 17 Pro",
  A3258: "iPhone 17",
  A3519: "iPhone 17",
  A3521: "iPhone 17",
  A3520: "iPhone 17",
  A3260: "iPhone Air",
  A3516: "iPhone Air",
  A3518: "iPhone Air",
  A3517: "iPhone Air",
  A3212: "iPhone 16e",
  A3408: "iPhone 16e",
  A3410: "iPhone 16e",
  A3409: "iPhone 16e",
  A3084: "iPhone 16 Pro Max",
  A3295: "iPhone 16 Pro Max",
  A3297: "iPhone 16 Pro Max",
  A3296: "iPhone 16 Pro Max",
  A3083: "iPhone 16 Pro",
  A3292: "iPhone 16 Pro",
  A3294: "iPhone 16 Pro",
  A3293: "iPhone 16 Pro",
  A3082: "iPhone 16 Plus",
  A3289: "iPhone 16 Plus",
  A3291: "iPhone 16 Plus",
  A3290: "iPhone 16 Plus",
  A3081: "iPhone 16",
  A3286: "iPhone 16",
  A3288: "iPhone 16",
  A3287: "iPhone 16",
  A2849: "iPhone 15 Pro Max",
  A3105: "iPhone 15 Pro Max",
  A3108: "iPhone 15 Pro Max",
  A3106: "iPhone 15 Pro Max",
  A2848: "iPhone 15 Pro",
  A3101: "iPhone 15 Pro",
  A3104: "iPhone 15 Pro",
  A3102: "iPhone 15 Pro",
  A2847: "iPhone 15 Plus",
  A3093: "iPhone 15 Plus",
  A3096: "iPhone 15 Plus",
  A3094: "iPhone 15 Plus",
  A2846: "iPhone 15",
  A3089: "iPhone 15",
  A3092: "iPhone 15",
  A3090: "iPhone 15",
  A2651: "iPhone 14 Pro Max",
  A2893: "iPhone 14 Pro Max",
  A2896: "iPhone 14 Pro Max",
  A2895: "iPhone 14 Pro Max",
  A2894: "iPhone 14 Pro Max",
  A2650: "iPhone 14 Pro",
  A2889: "iPhone 14 Pro",
  A2892: "iPhone 14 Pro",
  A2891: "iPhone 14 Pro",
  A2890: "iPhone 14 Pro",
  A2632: "iPhone 14 Plus",
  A2885: "iPhone 14 Plus",
  A2888: "iPhone 14 Plus",
  A2887: "iPhone 14 Plus",
  A2886: "iPhone 14 Plus",
  A2649: "iPhone 14",
  A2881: "iPhone 14",
  A2884: "iPhone 14",
  A2883: "iPhone 14",
  A2882: "iPhone 14",
  A2595: "iPhone SE (3ª geração)",
  A2782: "iPhone SE (3ª geração)",
  A2784: "iPhone SE (3ª geração)",
  A2785: "iPhone SE (3ª geração)",
  A2783: "iPhone SE (3ª geração)",
  A2484: "iPhone 13 Pro Max",
  A2641: "iPhone 13 Pro Max",
  A2644: "iPhone 13 Pro Max",
  A2645: "iPhone 13 Pro Max",
  A2643: "iPhone 13 Pro Max",
  A2483: "iPhone 13 Pro",
  A2636: "iPhone 13 Pro",
  A2639: "iPhone 13 Pro",
  A2640: "iPhone 13 Pro",
  A2638: "iPhone 13 Pro",
  A2482: "iPhone 13",
  A2631: "iPhone 13",
  A2634: "iPhone 13",
  A2635: "iPhone 13",
  A2633: "iPhone 13",
  A2481: "iPhone 13 mini",
  A2626: "iPhone 13 mini",
  A2629: "iPhone 13 mini",
  A2630: "iPhone 13 mini",
  A2628: "iPhone 13 mini",
  A2342: "iPhone 12 Pro Max",
  A2410: "iPhone 12 Pro Max",
  A2412: "iPhone 12 Pro Max",
  A2411: "iPhone 12 Pro Max",
  A2341: "iPhone 12 Pro",
  A2406: "iPhone 12 Pro",
  A2408: "iPhone 12 Pro",
  A2407: "iPhone 12 Pro",
  A2172: "iPhone 12",
  A2402: "iPhone 12",
  A2404: "iPhone 12",
  A2403: "iPhone 12",
  A2176: "iPhone 12 mini",
  A2398: "iPhone 12 mini",
  A2400: "iPhone 12 mini",
  A2399: "iPhone 12 mini",
  A2275: "iPhone SE (2ª geração)",
  A2298: "iPhone SE (2ª geração)",
  A2296: "iPhone SE (2ª geração)",
  A2160: "iPhone 11 Pro",
  A2217: "iPhone 11 Pro",
  A2215: "iPhone 11 Pro",
  A2161: "iPhone 11 Pro Max",
  A2220: "iPhone 11 Pro Max",
  A2218: "iPhone 11 Pro Max",
  A2111: "iPhone 11",
  A2223: "iPhone 11",
  A2221: "iPhone 11",
  A1920: "iPhone XS",
  A2097: "iPhone XS",
  A2098: "iPhone XS",
  A2099: "iPhone XS",
  A2100: "iPhone XS",
  A1921: "iPhone XS Max",
  A2101: "iPhone XS Max",
  A2102: "iPhone XS Max",
  A2103: "iPhone XS Max",
  A2104: "iPhone XS Max",
  A1984: "iPhone XR",
  A2105: "iPhone XR",
  A2106: "iPhone XR",
  A2107: "iPhone XR",
  A2108: "iPhone XR",
  A1865: "iPhone X",
  A1901: "iPhone X",
  A1902: "iPhone X",
  A1863: "iPhone 8",
  A1905: "iPhone 8",
  A1906: "iPhone 8",
  A1864: "iPhone 8 Plus",
  A1897: "iPhone 8 Plus",
  A1898: "iPhone 8 Plus",
  A1660: "iPhone 7",
  A1778: "iPhone 7",
  A1779: "iPhone 7",
  A1661: "iPhone 7 Plus",
  A1784: "iPhone 7 Plus",
  A1785: "iPhone 7 Plus",
  A1723: "iPhone SE (1ª geração)",
  A1662: "iPhone SE (1ª geração)",
  A1724: "iPhone SE (1ª geração)",
  A1633: "iPhone 6s",
  A1688: "iPhone 6s",
  A1700: "iPhone 6s",
  A1634: "iPhone 6s Plus",
  A1687: "iPhone 6s Plus",
  A1699: "iPhone 6s Plus",
  A1549: "iPhone 6",
  A1586: "iPhone 6",
  A1589: "iPhone 6",
  A1522: "iPhone 6 Plus",
  A1524: "iPhone 6 Plus",
  A1593: "iPhone 6 Plus",
  A1453: "iPhone 5s",
  A1457: "iPhone 5s",
  A1518: "iPhone 5s",
  A1528: "iPhone 5s",
  A1530: "iPhone 5s",
  A1533: "iPhone 5s",
  A1456: "iPhone 5c",
  A1507: "iPhone 5c",
  A1516: "iPhone 5c",
  A1529: "iPhone 5c",
  A1532: "iPhone 5c",
  A1428: "iPhone 5",
  A1429: "iPhone 5",
  A1442: "iPhone 5",
  A1431: "iPhone 4s",
  A1387: "iPhone 4s",
  A1349: "iPhone 4",
  A1332: "iPhone 4",
  A1325: "iPhone 3GS",
  A1303: "iPhone 3GS",
  A1324: "iPhone 3G",
  A1241: "iPhone 3G",
  A1203: "iPhone",
}

/** Cores/capacidades dos aparelhos antigos, que não estão em APPLE_MODELOS. */
const VARIANTES_ANTIGAS: Record<string, { capacidades: string[]; cores: string[] }> = {
  "iPhone 17e": { capacidades: ["256GB","512GB"], cores: ["Preto","Branco","Rosa-pálido"] },
  "iPhone 17 Pro Max": { capacidades: ["256GB","512GB","1TB","2TB"], cores: ["Prateado","Laranja-cósmico","Azul-intenso"] },
  "iPhone 17 Pro": { capacidades: ["256GB","512GB","1TB"], cores: ["Prateado","Laranja-cósmico","Azul-intenso"] },
  "iPhone 17": { capacidades: ["256GB","512GB"], cores: ["Preto","Branco","Azul-névoa","Sálvia","Lavanda"] },
  "iPhone Air": { capacidades: ["256GB","512GB","1TB"], cores: ["Preto-espacial","Branco-nuvem","Dourado-claro","Azul-céu"] },
  "iPhone 16e": { capacidades: ["128GB","256GB","512GB"], cores: ["preto","branco"] },
  "iPhone 16 Pro Max": { capacidades: ["256GB","512GB","1TB"], cores: ["titânio preto","titânio branco","titânio natural","titânio-deserto"] },
  "iPhone 16 Pro": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["titânio preto","titânio branco","titânio natural","titânio-deserto"] },
  "iPhone 16 Plus": { capacidades: ["128GB","256GB","512GB"], cores: ["preto","branco","rosa","verde-acinzentado","ultramarino"] },
  "iPhone 16": { capacidades: ["128GB","256GB","512GB"], cores: ["preto","branco","rosa","verde-acinzentado","ultramarino"] },
  "iPhone 15 Pro Max": { capacidades: ["256GB","512GB","1TB"], cores: ["titânio preto","titânio branco","titânio azul","titânio natural"] },
  "iPhone 15 Pro": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["titânio preto","titânio branco","titânio azul","titânio natural"] },
  "iPhone 15 Plus": { capacidades: ["128GB","256GB","512GB"], cores: ["preto","azul","verde","amarelo","rosa"] },
  "iPhone 15": { capacidades: ["128GB","256GB","512GB"], cores: ["preto","azul","verde","amarelo","rosa"] },
  "iPhone 14 Pro Max": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["prateado","dourado","preto-espacial","roxo-profundo"] },
  "iPhone 14 Pro": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["prateado","dourado","preto-espacial","roxo-profundo"] },
  "iPhone 14 Plus": { capacidades: ["128GB","256GB","512GB"], cores: ["meia-noite","estelar","(PRODUCT)RED","azul","roxo","amarelo"] },
  "iPhone 14": { capacidades: ["128GB","256GB","512GB"], cores: ["meia-noite","estelar","(PRODUCT)RED","azul","roxo","amarelo"] },
  "iPhone SE (3ª geração)": { capacidades: ["64GB","128GB","256GB"], cores: ["(PRODUCT)RED","estelar","meia-noite"] },
  "iPhone 13 Pro Max": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["grafite","dourado","prateado","azul-Sierra","verde-alpino"] },
  "iPhone 13 Pro": { capacidades: ["128GB","256GB","512GB","1TB"], cores: ["grafite","dourado","prateado","azul-Sierra","verde-alpino"] },
  "iPhone 13": { capacidades: ["128GB","256GB","512GB"], cores: ["(PRODUCT)RED","estelar","meia-noite","azul","rosa","verde"] },
  "iPhone 13 mini": { capacidades: ["128GB","256GB","512GB"], cores: ["(PRODUCT)RED","estelar","meia-noite","azul","rosa","verde"] },
  "iPhone 12 Pro Max": { capacidades: ["128GB","256GB","512GB"], cores: ["prateado","grafite","dourado","azul-Pacífico"] },
  "iPhone 12 Pro": { capacidades: ["128GB","256GB","512GB"], cores: ["prateado","grafite","dourado","azul-Pacífico"] },
  "iPhone 12": { capacidades: ["64GB","128GB","256GB"], cores: ["preto","branco","(PRODUCT)RED","verde","azul","roxo"] },
  "iPhone 12 mini": { capacidades: ["64GB","128GB","256GB"], cores: ["preto","branco","(PRODUCT)RED","verde","azul","roxo"] },
  "iPhone SE (2ª geração)": { capacidades: ["64GB","128GB","256GB"], cores: ["branco","preto","(PRODUCT)RED"] },
  "iPhone 11 Pro": { capacidades: ["64GB","256GB","512GB"], cores: ["prateado","cinza-espacial","dourado","verde meia-noite"] },
  "iPhone 11 Pro Max": { capacidades: ["64GB","256GB","512GB"], cores: ["prateado","cinza-espacial","dourado","verde meia-noite"] },
  "iPhone 11": { capacidades: ["64GB","128GB","256GB"], cores: ["roxo","verde","amarelo","preto","branco","(PRODUCT)RED"] },
  "iPhone XS": { capacidades: ["64GB","256GB","512GB"], cores: ["prateado","cinza-espacial","dourado"] },
  "iPhone XS Max": { capacidades: ["64GB","256GB","512GB"], cores: ["prateado","cinza-espacial","dourado"] },
  "iPhone XR": { capacidades: ["64GB","128GB","256GB"], cores: ["preto","branco","azul","amarelo","coral","(PRODUCT)RED"] },
  "iPhone X": { capacidades: ["64GB","256GB"], cores: ["prateado","cinza-espacial"] },
  "iPhone 8": { capacidades: ["64GB","128GB","256GB"], cores: ["dourado","prateado","cinza-espacial e (PRODUCT)RED"] },
  "iPhone 8 Plus": { capacidades: ["64GB","128GB","256GB"], cores: ["dourado","prateado","cinza-espacial e (PRODUCT)RED"] },
  "iPhone 7": { capacidades: ["32GB","128GB","256GB"], cores: ["preto matte","preto brilhante","dourado","ouro rosa","prateado","(PRODUCT)RED"] },
  "iPhone 7 Plus": { capacidades: ["32GB","128GB","256GB"], cores: ["preto matte","preto brilhante","dourado","ouro rosa","prateado","(PRODUCT)RED"] },
  "iPhone SE (1ª geração)": { capacidades: ["16GB","32GB","64GB","128GB"], cores: ["cinza-espacial","prateado","dourado","ouro rosa"] },
  "iPhone 6s": { capacidades: ["16GB","32GB","64GB","128GB"], cores: ["cinza-espacial","prateado","dourado","ouro rosa"] },
  "iPhone 6s Plus": { capacidades: ["16GB","32GB","64GB","128GB"], cores: ["cinza-espacial","prateado","dourado","ouro rosa"] },
  "iPhone 6": { capacidades: ["16GB","32GB","64GB","128GB"], cores: ["cinza-espacial","prateado","dourado"] },
  "iPhone 6 Plus": { capacidades: ["16GB","64GB","128GB"], cores: ["cinza-espacial","prateado","dourado"] },
  "iPhone 5s": { capacidades: ["16GB","32GB","64GB"], cores: ["cinza-espacial","prateado","dourado"] },
  "iPhone 5c": { capacidades: ["8GB","16GB","32GB"], cores: ["branco","azul","rosa","verde","amarelo"] },
  "iPhone 5": { capacidades: ["16GB","32GB","64GB"], cores: ["preto","branco"] },
  "iPhone 4s": { capacidades: ["8GB","16GB","32GB","64GB"], cores: ["preto","branco"] },
  "iPhone 4": { capacidades: ["8GB","16GB","32GB"], cores: ["preto","branco"] },
  "iPhone 3GS": { capacidades: ["8GB","16GB","32GB"], cores: ["preto","branco"] },
  "iPhone 3G": { capacidades: ["8GB","16GB"], cores: [] },
  "iPhone": { capacidades: ["4GB","8GB","16GB"], cores: [] },
}

/**
 * Procura pelo número de modelo. Aceita o código solto ("A2849") ou dentro de um
 * texto, porque costuma vir copiado da linha inteira de Ajustes.
 * Devolve null quando não reconhece — aí o cadastro segue pelo catálogo.
 */
export function buscarModeloApple(texto: string): (ModeloApple & { codigo: string }) | null {
  const t = (texto || '').toUpperCase()
  const m = /A\d{3,4}/.exec(t)
  if (!m) return null
  const nome = NUMERO_MODELO_APPLE[m[0]]
  if (!nome) return null
  const curado = APPLE_MODELOS.find((x) => x.nome.toLowerCase() === nome.toLowerCase())
  const antigo = VARIANTES_ANTIGAS[nome]
  return {
    codigo: m[0],
    modelo: curado?.nome ?? nome,
    capacidades: curado?.armazenamentos ?? antigo?.capacidades ?? [],
    cores: curado?.cores ?? antigo?.cores ?? [],
  }
}
